# This file is part of the Vagrant config, and gets overwritten on each
# `vagrant provision`.

. ~/venv/bin/activate
cd ~/app

export DJANGO_SETTINGS_MODULE="thinkingweekly.settings.development"
export USE_FILESYSTEM_STORAGE=true

if [ -f "/home/vagrant/app/settings_secret.sh" ]; then
    . /home/vagrant/app/settings_secret.sh
fi
