# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 14:25
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_url', models.URLField(help_text='Ideally this should be a URL for the event itself (not the general website of the organiser) and it should be the authoritative source of the event, not some other site that links to it. If there is no single URL then a more general URL can be used, like the website of the organisation.')),
                ('starts_at', models.DateTimeField(help_text='The time the event starts, or if it says to arrive early, then the arrival time')),
                ('extra_twitter_handle', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('twitter_handle', models.CharField(blank=True, help_text='With the leading @, eg @newsfromnowhere', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('twitter_handle', models.CharField(blank=True, help_text='With the leading @, eg @LEAFonBoldSt', max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(help_text='The group or organisations (if any) that organised this event. This may be the same as the venue, eg @LivUni and @newsfromnowhere or it may be separate, like how @Igniteliv is the organisation and they typically host in LEAF tea shop', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Organiser'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Venue'),
        ),
    ]
