# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue_sort_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
