# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_url_to_venue_and_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(blank=True, help_text='*IF different from the Venue, the group or organisations (if any) that organised this event, for example @Igniteliv is the organisation beind Ignite, which is usually hosted in LEAF tea shop', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Organiser'),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
