# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160724_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('start_date', models.DateField(primary_key=True, serialize=False)),
                ('end_date', models.DateField()),
                ('have_posted_email', models.BooleanField(default=False)),
                ('have_posted_facebook', models.BooleanField(default=False)),
                ('have_posted_twitter', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['starts_at']},
        ),
        migrations.AlterUniqueTogether(
            name='update',
            unique_together=set([('start_date', 'end_date')]),
        ),
    ]
