# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_update_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='have_posted_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='have_posted_twitter',
            field=models.BooleanField(default=False),
        ),
    ]
