# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_have_posted_facebook_twitter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='ready_to_post',
            field=models.BooleanField(default=False, help_text='Enable this to schedule the update to be posted automatically (betweem 9am-11am on Monday).'),
        ),
    ]
