# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_update_ready_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text="Add this to give the venue its own web page. Add with care, since it shouldn't be changed after it's set.", null=True),
        ),
    ]
