# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_venue_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='This should be an image which would complement the event listing.', null=True),
        ),
    ]
