# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import thinkingweekly.apps.events.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_add_external_image_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='By default, this will be automatically downloaded from the external_image_url field.', null=True, upload_to=thinkingweekly.apps.events.models.make_event_image_filename),
        ),
    ]
